### ISSUE TITLE
start dates

### ISSUE THREAD

**Issue by batemapf** [18F/partnership-playbook#19]
per @aaronsnow, the playbook should make it clear that we are not obligated to begin work "as soon as the ink is dry" on an agreement. start dates should be something that are discussed and resolved prior to the agreement is signed based on the staff and resources available.

**Comment by batemapf** [comment]
sorry, should have said, "if the playbook doesn't already..."

**Comment by wslack** [comment]
I'm not sure where this would go. This playbook isn't about the operations of working with us (IAAs, details, etc etc), but about _what the experience of working with us is like_. @batemapf, could this go into the intake website instead?

**Comment by batemapf** [comment]
not sure either, just carrying out the ask of our fearless leader. i think
the idea is to make it clear to our clients that start dates are more about
setting the project up for success, as opposed to getting started as soon
as possible.

On Thu, Feb 25, 2016 at 2:15 PM, Will Slack notifications@github.com
wrote:

> I'm not sure where this would go. This playbook isn't about the operations
> of working with us (IAAs, details, etc etc), but about _what the
> experience of working with us is like_. @batemapf
> https://github.com/batemapf, could this go into the intake website
> instead?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/partnership-playbook/issues/19#issuecomment-188936603
> .

## 

Patrick F. Bateman
Operations Director
18F
U.S. General Services Administration

**Comment by wslack** [comment]
Closing in favor of the other issue.
