### ISSUE TITLE
Bring playbook into 18f.gsa.gov

### ISSUE THREAD

**Issue by awfrancisco** [18F/partnership-playbook#29]
Research conducted by the 18F site team shows that users are confused when they get to the partnership playbook from the 18F site and 1) the design is unexpectedly different, 2) there is no navigation back to the 18F site. 

We should bring the partnership playbook into the site using the same navigation and styling as the [new join guide](https://18f.gsa.gov/join/).

**Comment by elainekamlley** [comment]
We did! https://18f.gsa.gov/partnership-principles/
