### ISSUE TITLE
Switch main branch to master

### ISSUE THREAD

**Issue by gboone** [18F/partnership-playbook#30]
I'm not an admin but someone who is should switch the main branch to master. That is the main branch Federalist will use to build the site. In the mean time, and once we're migrated to Federalist, any changes to `18f-pages` should get merged to `master` in order to be live

**Comment by wslack** [comment]
Will do that now Greg. Remember that for now, the live site will still serve from the 18f-pages branch, built by old Federalist.

**Comment by wslack** [comment]
done!
